version: '3.4'

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1431:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: hjkfd7bbfdmn3icz1s